INSERT INTO productos(nombre,etiquetas) values
('SMARTPHONE',ARRAY['TECNOLOGIA','CELULAR','INTERNET']),
('LIBRO',ARRAY['AVENTURA','ROMANCE','DRAMA']),
('LAPTOP',ARRAY['TECNOLOGIA','AMD','HP']);

INSERT INTO empleados(nombre,jefe_id) values
('LETICIA Z',NULL),
('LEO J',1),
('YARETH G',2),
('FABIAN S',2);

INSERT INTO rutas (ciudad_origen, ciudades_destino) VALUES
('SLP', ARRAY['QUERETARO', 'ZACATECAS', 'GUANAJUATO']),
('QUERETARO', ARRAY['CDMX', 'SLP', 'GUADALAJARA']),
('ZACATECAS', ARRAY['AGUASCALIENTES', 'SLP']),
('GUANAJUATO', ARRAY['SLP', 'LEON']),
('CDMX', ARRAY['QUERETARO', 'PUEBLA']),
('GUADALAJARA', ARRAY['QUERETARO', 'MANZANILLO']),
('AGUASCALIENTES', ARRAY['ZACATECAS']),
('LEON', ARRAY['GUANAJUATO']),
('PUEBLA', ARRAY['CDMX']),
('MANZANILLO', ARRAY['GUADALAJARA']);
