name: Test Arrays y Grafos

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar dependencias Python
        run: |
          python3 -m pip install psycopg2

      - name: Ejecutar scripts SQL
        run: |
          for f in *.sql; do
            echo "Ejecutando $f"
            psql postgresql://postgres:postgres@localhost:5432/postgres -f "$f"
          done

      - name: Ejecutar tests
        run: |
          python3 test/test_excercise.py
